baseURL = 'https://jrdnh.github.io/'
languageCode = 'en-us'
title = 'jrdnh'
theme = 'anubis'
paginate = 10
#disqusShortname = "yourdiscussshortname"
googleAnalytics = "G-12345"
enableRobotsTXT = true

#[menu]
#[[menu.main]]
#identifier = "archive"
#name = "Archive"
#title = "Archive"
#url = "/posts/"
#weight = 0

[params]
author = "jrdnh"
#email = "mail@example.org"
#avatar = "/images/me.png"
description = ""
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
mainSections = [ "posts",]
sectionsWithFullContentOnListPage = [ "notes",]
readMore = false
readNextPosts = 5
disableSummary = false
toc = true
tocWordCount = 300
copyCodeButton = true
rssAsSocialIcon = false
mathjax = false
utterancesRepo = ""
utterancesTheme = ""
utterancesIssue = ""
utterancesLabel = ""
graphcommentId = ""
GiscusRepo = ""
GiscusRepoId = ""
GiscusCategory = "Announcements"
GiscusCategoryId = ""
GiscusLazyLoad = false
[[params.social]]
id = "github"
name = "jrdnh"

[params.isso]
enabled = true
data = "https://comments.example.com/"
jsLocation = "https://comments.example.com/js/embed.min.js"
css = true
lang = "de"
replyToSelf = true
requireAuthor = true
requireEmail = true
id = "thread-id"
avatar = true
avatar-bg = "#f0f0f0"
feed = false

[params.UmamiAnalytics]
enabled = true
dnt = true
id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
datacache = false
url = "https://abc.example.com/umami.js"

[params.webmentions]
url = "https://yourdomain.com/webemntions/receive"
login = "hugo-theme-anubis"
pingback = true

[markup.goldmark.renderer]
unsafe = true
